### ISSUE TITLE
Map drivestick joystick inputs to Xbox controller

### ISSUE THREAD

**Issue by KyleQ1** [frc3512/Robot-2020#106]

**Comment by calcmogul** [comment]
This will require replacing any instances of `frc::Joystick` with indices 0 or 1 with a single instance of `frc::XboxController`. You'll find them in the subsystem periodic functions.

The header for `frc::XboxController` is `<frc/XboxController.h>` and the docs are at https://first.wpi.edu/FRC/roborio/release/docs/cpp/classfrc_1_1XboxController.html.

**Comment by KyleQ1** [comment]
Drivers prefer joysticks over Xbox controllers.
