### ISSUE TITLE
Add ultrasonic code for Galactic Search

### ISSUE THREAD

**Issue by KyleQ1** [frc3512/Robot-2020#126]
Here's a reference you can use from [maxbotix.](https://www.maxbotix.com/firstrobotics) 
- Use the [analoginput class](https://first.wpi.edu/FRC/roborio/release/docs/cpp/classfrc_1_1AnalogInput.html) from WPILib to make the encoder
- Get the value from the sensor periodically
- Apply a [linear filter](https://docs.wpilib.org/en/latest/docs/software/advanced-controls/filters/linear-filter.html?highlight=linear%20filter) on the value you're receiving 
- ~~Use this `units::meter_t currentDistance = units::centimeter_t{rawValue * 0.125};` to get the distance of the object in meters.~~ Docs bad instead do this https://github.com/frc3512/Robot-2020/issues/126#issuecomment-769546005
- Add this to the galactic search autonomous mode
- If the ball is in range then choose one autonomous path over another

**Comment by calcmogul** [comment]
Do this instead:
```cpp
frc::AnalogInput ultrasonic{0};
units::meter_t distance = units::volt_t{ultrasonic.GetVoltage()} * 1_m / 1_V;
```
