### ISSUE TITLE
Create an "enable diagnostics" NT bool to enable/disable setting all other diagnostic NT values

### ISSUE THREAD

**Issue by calcmogul** [frc3512/Robot-2020#135]
This will save network bandwidth. The default value should be false. The user can set the value to true within OutlineViewer to enable diagnotsics.

We could also check `DriverStation::GetInstance().IsFMSConnected()` to automatically disable live diagnostics during competition.

**Comment by KyleQ1** [comment]
We may be able to add this to NetworkTableUtil to disable all entries at once.

**Comment by calcmogul** [comment]
How? We need this to work at runtime, not just on startup.
