### ISSUE TITLE
Refactor our Encoder things into specific device classes at some point with the conversion factors built in

### ISSUE THREAD

**Issue by KyleQ1** [frc3512/Robot-2020#43]

**Comment by KyleQ1** [comment]
Do we still want to add this to our code at some point?

**Comment by calcmogul** [comment]
To elaborate on this issue:

Instead of a generic Encoder class we configure distance per pulse and other things with via SetDistancePerPulse(), we'd have a class like AMT103V with an encoder pulses per revolution enum, and include the 2pi conversion internally from rotary to linear motion.

**Comment by calcmogul** [comment]
This abstraction won't save much work, and ends up just being more code to maintain.
