### ISSUE TITLE
Implement leading/lagging the target while the drivetrain is moving

### ISSUE THREAD

**Issue by KyleQ1** [frc3512/Robot-2020#44]
* Our current solution doesn't lead/lag because it assumes instantaneous time of flight. We need to include the ball's actual velocity vector out of the shooter and the drivetrain velocity vector to find the desired turret angle relative to the chassis.

* Here's an article on the math we need with some messy code: https://www.codeproject.com/articles/990452/interception-of-two-moving-objects-in-d-space

**Comment by willji0023** [comment]
This is what I got. Thoughts?
https://docs.google.com/drawings/d/18WzkPOciQZ1gUmpbT0Rz63n-URB6hmX9EIIBCdBfPaA/edit?usp=sharing

**Comment by calcmogul** [comment]
You should explain your setup (lay out your definitions like the coordinate frame, what vectors are involved, etc.) and show more of your work. It isn't clear from the diagram alone that the equation you got at the end is correct, so I'm having trouble verifying it.
