### ISSUE TITLE
Make a way to stream controller data live to a python plotting script

### ISSUE THREAD

**Issue by calcmogul** [frc3512/Robot-2020#64]
The current CSV approach is hard to manage remotely for testing/tuning purposes because it isn't clear which file contains the desired data. Furthermore, the CSVs don't reliably write to the roboRIO's flash.

This is basically what https://github.com/frc3512/LiveGrapher does, but I think we can do better now from a usability perspective.

**Comment by KyleQ1** [comment]
How is it going to be different from LiveGrapher?

**Comment by calcmogul** [comment]
We should make a wrapper around the LiveGrapher host library (the part that lives on the robot) to automatically plot the controller data. We can make a modified version of ControllerLogger that uses LiveGrapher as the backend instead of .csv files.
