### ISSUE TITLE
Change intake logic from if statements to a state machine

### ISSUE THREAD

**Issue by KyleQ1** [frc3512/Robot-2020#75]

**Comment by calcmogul** [comment]
The relevant flags should be "flywheel started", "flywheel at goal", "upper sensor blocked", and "lower sensor blocked". Write out a table of those with each combination of true and false (there should be 16 combinations). Those are your states.

Then, write what each motor should be allowed to do in each state. That could be an umbrella of stuff like "listen to the driver input on this specific actuator on the robot", or "run these mechanisms at these speeds/set their speeds to zero".
