### ISSUE TITLE
Add conveyor logic unit test

### ISSUE THREAD

**Issue by calcmogul** [frc3512/Robot-2020#97]
Make a unit test that tracks the positions of some fake balls, move them when the user logic tells the motor to move, and set the sensor state when a ball passes it using DigitalInputSim. The unit test would be enforcing some of the more basic logic defined in docs/intake-io-table.md.

**Comment by KyleQ1** [comment]
This could also be working in combination with the flywheel using JoystickSim to further enforce the logic defined in docs/intake-io-table.md.

**Comment by calcmogul** [comment]
If we had a way to automate going from the intake I/O table to code, we probably wouldn't need unit tests of the conveyor logic impl, just a way to confirm the transformation was done correctly.

**Comment by calcmogul** [comment]
OBE since season is now over.
